# frozen_string_literal: true

tap 'buo/cask-upgrade', trusted: true # auto-upgrade casks

brew 'bat' # `cat` replacement
brew 'btop' # `htop` replacement
brew 'curl' # CLI for transferring data
brew 'coreutils' # GNU core utilities
brew 'dockutil' # CLI for MacOS Dock management
brew 'eza' # `ls` replacement
brew 'fd' # `find` replacement
brew 'findutils' # GNU find utilities
brew 'fzf' # Fuzzy finder
brew 'gh' # GitHub CLI
brew 'git' # Version control
brew 'gum' # Go based interactive shell script generator
brew 'gs' # Postscript and PDF interpreter
brew 'htop' # `top` replacement
brew 'imagemagick' # Image processing
brew 'jq' # JSON processor
brew 'just' # Script runner
brew 'lazygit' # Git Terminal UI
brew 'libyaml' # dependency for ruby
brew 'luarocks' # dependency for nvim
brew 'mas' # Mac App Store
brew 'mise' # dev tool versions, tasks and environment manager
brew 'neovim' # Preferred text editor
brew 'pkl-lsp' # Apple's configuration language server
brew 'ripgrep' # `grep` replacement
brew 'stow' # Symlink manager
brew 'tectonic' # LaTeX engine
brew 'tmux' # Terminal multiplexer
brew 'vivid' # `LS_COLORS` generator
brew 'wallpaper' # macOS wallpaper manager
brew 'wget' # GNU Wget
brew 'yazi' # File manager in terminal
brew 'yq' # YAML processor
brew 'zoxide' # `cd` replacement
brew 'zsh' # Shell

cask '1password' # Password manager
cask '1password-cli' # 1Password CLI
cask 'betterdisplay' # Display configuration manager
cask 'claude-code' # AI coding agent
cask 'docker-desktop' # Containerization
cask 'google-chrome' # Browser
cask 'ghostty' # Terminal emulator
cask 'gpg-suite' # GPG keychain
cask 'hammerspoon' # macOS automation
cask 'imageoptim' # Image optimizer
cask 'insomnium' # HTTP Client
cask 'obsidian' # Note-taking
cask 'wezterm@nightly', args: { greedy_latest: true } # Terminal emulator

mas '1Password for Safari', id: 1_569_813_296
mas 'Yubico Authenticator', id: 1_497_506_650

if ENV['HOMEBREW_PROFILE'] == 'personal' # Personal profile
  cask 'discord' # Chat
  cask 'softraid' # Disk management
  cask 'whatsapp' # Messenger
end
