[tools]
rust = "nightly"
cargo-binstall = "latest"
node = { version = "25", postinstall = "mise run global-install-packages-npm" }
python = { version = "3.13", postinstall = "mise run global-install-packages-python" }
ruby = { version = "latest", postinstall = "mise run global-install-packages-ruby" }

bun = "latest"
go = "latest"
uv = "latest"
delta = "latest"
stylua = "latest"
prettier = "latest"
tree-sitter = "latest"
markdownlint-cli2 = "latest"
opencode = "latest"

"npm:@mermaid-js/mermaid-cli" = { version = "latest", install_env = { PUPPETEER_SKIP_DOWNLOAD = "1" } }
"npm:mcp-hub" = "latest"
"npm:@github/copilot" = "latest"
"npm:@tobilu/qmd" = "latest"
