# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
---
git:
  diffRenderers:
    - colorArg: always
      command: >-
        delta --features='catppuccin-mocha zebra-dark' --paging=never --line-numbers
        --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
