# frozen_string_literal: true

tap 'buo/cask-upgrade'

brew 'mas'
brew 'zsh'
brew 'git'
brew 'lazygit'
brew 'coreutils'
brew 'neovim'
brew 'stow'
brew 'fzf'
brew 'fd'
brew 'bat'
brew 'ripgrep'
brew 'zoxide'
brew 'node'
brew 'go'
brew 'ruby'
brew 'wget'
brew 'htop'

cask '1password'
cask 'hammerspoon'
cask 'wezterm'
cask 'obsidian'
cask 'betterdisplay'
cask 'imageoptim'
cask 'discord'
cask 'gpg-suite'

mas 'WhatsApp Messenger', id: 310_633_997
mas '1Password for Safari', id: 1_569_813_296
