# frozen_string_literal: true

tap 'buo/cask-upgrade' # auto-upgrade casks

brew 'mas' # Mac App Store
brew 'zsh' # Shell
brew 'eza' # `ls` replacement
brew 'vivid' # `LS_COLORS` generator
brew 'git' # Version control
brew 'lazygit' # Git Terminal UI
brew 'coreutils' # GNU core utilities
brew 'wget' # GNU Wget
brew 'curl' # CLI for transferring data
brew 'neovim' # Preferred text editor
brew 'stow' # Symlink manager
brew 'fzf' # Fuzzy finder
brew 'fd' # `find` replacement
brew 'bat' # `cat` replacement
brew 'ripgrep' # `grep` replacement
brew 'zoxide' # `cd` replacement
brew 'libyaml' # dependency for ruby
brew 'luarocks' # dependency for nvim
brew 'mise' # version, environment manager
brew 'docker' # Container manager
brew 'htop' # `top` replacement
brew 'yazi' # File manager in terminal
brew 'gum' # Go based interactive shell script generator
brew 'jq' # JSON processor
brew 'just' # Command runner

cask '1password' # Password manager
cask 'hammerspoon' # macOS automation
cask 'wezterm@nightly' # Terminal emulator
cask 'obsidian' # Note-taking
cask 'betterdisplay' # Display configuration manager
cask 'imageoptim' # Image optimizer
cask 'discord' # Chat app
cask 'gpg-suite' # GPG keychain
cask 'google-chrome'

# mas 'WhatsApp Messenger', id: 310_633_997
mas '1Password for Safari', id: 1_569_813_296
